### ISSUE TITLE
Instagram Phishlets Cookies

### ISSUE THREAD

**Issue by TheSilentNoob** [An0nUD4Y/Evilginx2-Phishlets#13]
Hello , I use evilginx2 with this instagram phishlets , the problem is there, when i go to my instagram dns and all , its working correctly, my only problem is when i go on my "infected page" instagram asking me for cookies like its asking , "would you allow cookies for this browser" but when i click on allow it isn't do anythings my only fix is to inspect element and remove the div of the asking cookie "presentation" div , and  the problem is there , is there a fix to remove this pop-up

**Comment by rzmpzgeviii** [comment]
@TheSilentNoob @An0nUD4Y 
Got the exact same problem. Does any of you know how to resolve this?
