### ISSUE TITLE
Instagram Cookie Banner Bug

### ISSUE THREAD

**Issue by rzmpzgeviii** [An0nUD4Y/Evilginx2-Phishlets#14]
Hey @An0nUD4Y , you seem very experienced with evilginx and phishlets do you know by any chance how to resolve the cookie banner bug? The banner cant be accepted nor closed. Any help would be really appreciated!
![1](https://user-images.githubusercontent.com/101715188/197639790-cdc201da-5385-4ba0-8b5d-a0fc07415f6d.PNG)

**Comment by MlodyG420** [comment]
Have you been able to solve this issue? I've got the same problem.

**Comment by An0nUD4Y** [comment]
@rzmpzgeviii , Its impossible to provide support of each phishlets. But for the current instagram phishlet issue, i will recommend to look at the requests carefully and compare them with original requests to instagram, and make changes accordingly. There may be some detection in place by instagram.
