### ISSUE TITLE
Getting error with yahoo phishlets

### ISSUE THREAD

**Issue by DBarvni** [An0nUD4Y/Evilginx2-Phishlets#15]
Hello @An0nUD4Y , Getting errors with yahoo phishlets,  while trying for the local machine it works fine, but as soon as I upload phislets to the server. It stopped working. while redirecting to the password page., Any help would be really appreciated!
error:
"We are unable to process your request at this time Try after one hour"
![error](https://user-images.githubusercontent.com/116793540/198222992-455233f0-5af0-44c2-a2fd-9fbd95145da7.png)

**Comment by An0nUD4Y** [comment]
#14
