### ISSUE TITLE
web-app

### ISSUE THREAD

**Issue by pentest01** [An0nUD4Y/Evilginx2-Phishlets#18]
I followed all your instruction to get the web-app working, but when i run, i get this error

![image](https://user-images.githubusercontent.com/103268912/205105119-8668d1e4-eb09-41d3-aa7a-3acefc3b92b3.png)

![image](https://user-images.githubusercontent.com/103268912/205105211-9be0eb7e-495a-4b30-bbb4-dbc94c9c5fda.png)

and it runs without ssl.

**Comment by pentest01** [comment]
any way to get this to work?

**Comment by AnthraxBPLLC** [comment]
Create a .env file under web-panel folder and put this by doing nano .env and this 
SESSION_SECRET=secret

**Comment by c0dito** [comment]
login ?
pass ?

What values to use or where are set?

**Comment by c0dito** [comment]
"name" : "evilginx",
"password" : "evilginx",

**Comment by AnthraxBPLLC** [comment]
Inside the web panel folder under /.evilnginx/web-panel-Nginx, type this nano .env and put this value SESSION_SECRET=161760d1f7cd6a87d38c8c59a830314a if you want working for web panel with click on cookies automated convert to Jason contact me on telegram https://t.me/anthraxlinkers I got a version that sends to email, telegram,discord can do demonstration if you want

**Comment by AnthraxBPLLC** [comment]
the issue has been sloved you can closed this audry my friend

**Comment by pentest01** [comment]
Thank you all for the help.
