### ISSUE TITLE
Paypal detect proxy

### ISSUE THREAD

**Issue by Hawaii487** [An0nUD4Y/Evilginx2-Phishlets#19]
How to fix Paypal detecting proxy

**Comment by An0nUD4Y** [comment]
I can't provide support for each phishlet for obvious reasons.

Possible methods You can try.
- Debug how the paypal is detecting the proxy, and modify the proxy accordingly.
- Check if the Evilginx Easter Egg is not the reason.
- Research the cause and work on the fix.

For more accurate answer, You can create new issue with more details.
Also i am available to work as freelance on phishlets but only for red teams or for pentesting use cases of phishlets.
