### ISSUE TITLE
web-panel users.json

### ISSUE THREAD

**Issue by AnthraxBPLLC** [An0nUD4Y/Evilginx2-Phishlets#20]
Hello, I want to understand better about the panel. The code of users.json is like this.

`    {
        "name" : "evilginx",
        "password" : "evilginx",
        "id": "1"
    }
]`

The dose means the ID is intended to be the lures ID.
 Let's say the o365 ID is ID 4, so will I have to edit the user ID to be 4??

**Comment by An0nUD4Y** [comment]
No , the user ID is completely independent of lure ID's .
Those ID's are just user ID nothing else.

You can add new user as well.
For Ex.

```
   { "name" : "evilginx", "password" : "evilginx", "id": "1" } ]
   { "name" : "evilginx", "password" : "an0nud4y", "id": "2" } ]
```
