### ISSUE TITLE
iCloud phishlet error

### ISSUE THREAD

**Issue by inneedofassistance** [An0nUD4Y/Evilginx2-Phishlets#21]
Hey, your iCloud phishlet doesn't seem to be working. I set it up and everytime I go to the website an error box that says "Connection error" appears. How can I fix this?

**Comment by An0nUD4Y** [comment]
I can't provide support here for each phishlet for obvious reasons.
Look for possible requests failures and use burp to check each request manually and compare with original request , you can also use evilginx proxy feature to do that.
Also if you need it for pentesting or red teams , you can contact me on telegram , I can work on it as freelance.
Thanks.
