### ISSUE TITLE
Phishlets for EVILGINX 3.1?

### ISSUE THREAD

**Issue by Dazmed707** [An0nUD4Y/Evilginx2-Phishlets#25]
This repo found in 3.1 ?

**Comment by An0nUD4Y** [comment]
phishlets are compatible with v3.1 as well, make sure to check this. https://github.com/An0nUD4Y/Evilginx2-Phishlets#using-evilginx2-phishlets-with-evilginx3

**Comment by Mrsagacious** [comment]
> This repo found in 3.1 ?
i think this is covered in the course, do you have simple hacking course ?
