### ISSUE TITLE
These phishlets don’t work with newest evilginx3 update 

### ISSUE THREAD

**Issue by Johnnycage7734** [An0nUD4Y/Evilginx2-Phishlets#26]
I’ve tried the majority of these phishlets and I haven’t found not ONE that works in the latest Evilginx update. He added in the “readme” that you need to modify the evilginx3 source code to be able to support these phishlets and gives you the line you need to modify, but, line 909(as described in the “readme” isn’t even there, it’s a completely different line of code there. Could anyone share some tips on how they got them to work? (If anyone has) doesn’t seem like the author is here much to offer support. The problem I’m having with these phishlets is, as soon as I load into the url, it’s either outdated or there’s significant things missing like the webpage logo, or the page has no pictures, icons, OR, the page won’t let you type anything in, this rendering it useless.

**Comment by An0nUD4Y** [comment]
These phishlets are mostly to learn and surely won't work coz of frequent updates by the various websites.
Also with updates in evilginx the source code gets changed and its obvious that the code line no. won't be same.
Nearly all the parameters in v2 and v3 of evilginx phishlets are same.

To make these phishlets work you have to modify the phishlet and develop and new one.
