### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by jakre1234** [An0nUD4Y/Evilginx2-Phishlets#29]
Hi Uday,
Not an issue just wanted to know if these are updated and compatible with the new evilginx 2 ? Does these works with evilginx2 or they are from the version 1? I saw the author of evilginx removed all phishlets from public and made it a pro only feature, hoping to get these to work with evilginx 2.

Thanks and Regards,

**Comment by An0nUD4Y** [comment]
Try and test , Most of these need little changes and will eventually work with latest version of evilginx.
