### ISSUE TITLE
How to bypass gmail recaptcha?

### ISSUE THREAD

**Issue by bigherocenter** [An0nUD4Y/Evilginx2-Phishlets#34]
Hi, 
I found recaptcha url in accounts.google.com .
It's "https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LdD2OMZAAAAAAv2xVpeCk8yMtBtY3EhDWldrBbh&co=aHR0cHM6Ly9hY2NvdW50cy5z....s&hl=en&v=EGbODne6buzpTnWrrBprcfAY&theme=light&size=normal&cb=trcd4wrj9b4j"

So i try to replace aHR0cHM6Ly9hY2NvdW50cy5z[....] to co= co=aHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tOjQ0Mw.. , but it couldn't replace .
Please tell me how to replace it .

**Comment by itsdayztar1** [comment]
telegram https://t.me/nextgenerationphishing

**Comment by itsdayztar1** [comment]
why did u delete the simple solution?

**Comment by itsdayztar1** [comment]
evilginx makes capturing cookies seem like a big deal..

**Comment by Rastasau** [comment]
@itsdayztar1 pls can you tell me how to fix the issue stated in the thread? i dont know why everyone keeps making it such a big deal. you can write me.. suka.w1@hotmail.com

**Comment by Rastasau** [comment]
@itsdayztar1 you can also share your telegram and i will reach out

**Comment by An0nUD4Y** [comment]
Please follow the provided solution in readme file, Both methods still works.
