### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by chloemahachek** [An0nUD4Y/Evilginx2-Phishlets#37]
Warning: This individual is suspected of being a scammer. Do not make any purchases from them without using a secure escrow service or obtaining solid proof that they own the code they are offering for sale.

Please be careful when writing my name on Telegram. Many scammers create profiles similar to mine by altering letters in the username. My only official Telegram profile is https://t.me/blackdatabase. Always double-check the spelling: @B L A C K D A T A B A S E. If the spelling differs, it's not me.

The real developer of this project is [Insert Real Developer's Name or Alias], and they can be contacted directly at [Insert Developer's Contact Info, e.g., email or Telegram handle].

Stay vigilant to avoid fraud, and if you are unsure, confirm the identity before proceeding with any transactions.

**Comment by An0nUD4Y** [comment]
Ahh you missed the template placeholders.
